name = "AppleHealthParser"
uuid = "d1ed7681-0bdc-4b3e-a64e-a9a059b3ebfe"
authors = ["Sumanth Athreya Seshasayee <sumant28@hotmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
